Stop modifying PyGreSQL layout
Greengage has custom installation scripts for PyGreSQL to place module
to the dedicated direcory. There already was an issue with moving shared
library of the module to the proper directory level during migration to
python 3. Also, this approach makes impossible to use common
installation with pip. Further more, there is 10 years old issue with
pickling PyGreSQL exceptions:

```
>>> import pickle
>>> from pygresql import pg
>>> pickle.dumps(pg.DatabaseError())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.PicklingError: Can't pickle <class 'pg.DatabaseError'>: import
 of module 'pg' failed
```

This patch throw out additional directory layer for PyGreSQL and
implements a small shim python module to preserve compatibility with
existing Greengage codebase. So that `from pygresql.pg import DB` works
as expected.